### PR TITLE
Add Red Hat Certified Spinnaker  operator/installer

### PR DESCRIPTION
**Pull request by dommety**
I see issue #1544 closed. It was not reflected in the site. So re-submitting it again.

### CODE REVIEW

**Comment by 317brian** [comment]
https://github.com/spinnaker/spinnaker.github.io/pull/1544 was closed by @rebalag, who opened it. It wasn't merged, so it wouldn't show up on the site.

**Comment by dommety** [comment]
Brian,



He in-correctly closed it. So, I filed it again. Can we use this PR to get it resolved?  


Thank you,

Gopal




---- On Mon, 28 Oct 2019 15:29:20 -0700 brian-armory <notifications@github.com> wrote ----


https://github.com/spinnaker/spinnaker.github.io/pull/1544 was closed by https://github.com/rebalag, who opened it. It wasn't merged, so it wouldn't show up on the site.

**Comment by 317brian** [comment]
FYI @dorbin and @plumpy who were on the original issue.

**Comment by plumpy** [comment]
Is there any guidance about which to use under what circumstances? Why are there three operators?

**Comment by dommety** [comment]
@plumpy Incorporated review comments to provide clarity on the three operators.  Hope this is sufficient. Thanks.

**Comment by dorbin** [comment]
LGTM
@plumpy , what say ye?

**Review by plumpy — APPROVED** [review]

**Pull request merged**
