### PR TITLE
docs(bake/manifests): add namespace parameter in Helm bakery

### PR DESCRIPTION
**Pull request by posox**
Issue: https://github.com/spinnaker/spinnaker/issues/2909

### CODE REVIEW

**Review by dorbin — CHANGES_REQUESTED** [review]
@posox , could you update the screen shot too, to show the new field?

Thanks!

**Comment by posox** [comment]
@dorbin screenshot was updated.

**Review by lwander — APPROVED** [review]
Thanks!

**Comment by lwander** [comment]
Since @dorbin is OOO and the screenshot was updated I'll merge now

**Pull request merged**
