### PR TITLE
Updating the setup docs

### PR DESCRIPTION
**Pull request by riguy724**
I had some trouble with the naming conventions taking the "happy path" of spinnaker setup on AWS, I'm hoping these notes will help others avoid some of the time-sinks I ran in to.

### CODE REVIEW

**Comment by riguy724** [comment]
Updated with some wording changes here.

**Comment by rbuskens** [comment]
@riguy724 Do you want to incorporate @tomaslin's suggestion wrt 'matters' --> 'is important as'?

**Comment by riguy724** [comment]
Oh yeah, I thought I had, must've not pushed those changes up from local, let me do that.

**Comment by riguy724** [comment]
There we go! Updated to incorporate changes and squashed everything down to keep history clean.

**Comment by tomaslin** [comment]
LGTM. Thank you for your contribution and working through this with us.

**Comment by riguy724** [comment]
Yep no problem.

**Pull request merged**
