### PR TITLE
docs(dev-env): Removing ref to #gardening-feedback channel

### LINKED ISSUE #1869: Removing ref to #gardening-feedback channel
[Remove reference to #gardening-feedback channel as it no longer exists as a slack channel in Spinnaker slack](https://www.spinnaker.io/community/gardening/dev-environment/#help-us-improve-the-contributor-experience)

### PR DESCRIPTION
**Pull request by markjacksonfishing**
Fixes #1869 
Signed-off-by: markyjackson-taulia <marky.r.jackson@gmail.com>

### CODE REVIEW

**Comment by dorbin** [comment]
@dnilasor

**Comment by markjacksonfishing** [comment]
Not sure of the pr timeline for xs changes. Ping @dnilasor

**Review by dnilasor — APPROVED** [review]
There is a feedback channel called #gardening-anonymous where folks can leave anonymous feedback, so an alternative would be to link to that channel instead of removing it. I am OK with either.

**Comment by markjacksonfishing** [comment]
@dnilasor my vote would be to remove it entirely. Using the word `anonymous` assumes anamenity but that would not be the case of a public channel where the profile is linked to anything posted by the person posting.

**Comment by dnilasor** [comment]
Well, that's not exactly true @markyjackson-taulia. This isn't an anonymity bait' n switch, we are actually using a [slack-integrated anonymous feedback app](https://cloud-armory.slack.com/apps/A57EXBHND-abot-anonymous-poll-and-feedback) to collect feedback in that channel, so it truly is anonymous. 

You have my approval to remove it if that's your preference. I may introduce references to the #gardening-anonymous channel when I update the Spinnaker Gardening materials on the site here shortly and that can be a separate convo.

**Comment by markjacksonfishing** [comment]
Is this documented anywhere @dnilasor

**Comment by markjacksonfishing** [comment]
@dnilasor i feel for now this reference channel should be removed since it doesn’t exist.

**Comment by dnilasor** [comment]
I feel like we are going around and around in circles...I already said it is OK to remove it, and yes you should definitely remove the channel name that doesn't exist and either replace it with an existing channel name or not at all. _I have approved either of those activities._

It's documented in the poll/channel itself. Otherwise, not currently. As I said, I'll add clearer references to it in an upcoming PR.

FWIW, a channel labeled "gardening" might not ultimately be the best place to provide general feedback about Spinnaker dev environments, it's just where it started and our efforts on this are ongoing. Do note that anyone can create an anonymous poll in Spinnaker Slack using that bot, so feel free to use it if you like. Here is the FAQ: https://abot.app/faq

**Comment by markjacksonfishing** [comment]
You have the power to approve and merge 🙂

**Comment by dnilasor** [comment]
@markyjackson-taulia I don't have merge privileges on any spinnaker repositories. 
image

**Pull request merged**
