### PR TITLE
docs(setup): Adds Google I/O Codelab to quickstart page

### PR DESCRIPTION
**Pull request by skim1420**
@demobox, @lwander FYI, any objections/thoughts to this?

### CODE REVIEW

**Review by dorbin — COMMENTED** [review]
I was thinking of adding it to /guides/tutorials/codelabs/. Can we do both?

**Comment by skim1420** [comment]
sgtm, or if you're inclined to, even remove this one and only add to codelabs. Just wanted it represented somewhere, and I thought quickstart was a decent one.

On a broader sense, it raises what the purpose of the quickstart section is vs codelabs. We had discussed the notion that a general purpose quickstart often sets up wrong expectations with the user.

**Comment by demobox** [comment]
> even remove this one and only add to codelabs

I think adding it here risks confusing users in that the resulting instance here isn't accessible in the same way as one created by the Helm chart or Cloud Launcher, e.g. it's not created in a user's project or account.

+1 adding it [guides](https://www.spinnaker.io/guides/) and/or codelabs.

**Comment by skim1420** [comment]
sgtm, closing.

**Pull request closed without merging**
