### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by stephly07**
Suggestions on formatting (to be consistent with other pages) and edits to text to make the content more concise

### CODE REVIEW

**Comment by lilbobb** [comment]
Thanks

**Comment by lilbobb** [comment]
It's my first time. . I know little about it.

**Comment by stephly07** [comment]
It's my first time too :)

**Comment by dorbin** [comment]
You never forget your first...PR 🌞

**Review by dorbin — APPROVED** [review]

**Review by aleon1220 — COMMENTED** [review]
This is a good contribution. Reduces wording and makes the doc look very tidy.
Thanks so much.

**Pull request merged**
