### PR TITLE
fix(docs): broken swagger-ui link

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
cc @lwander

**Review by lwander — APPROVED** [review]

**Comment by lwander** [comment]
Thanks!

**Comment by lwander** [comment]
I don't think that link is correct, the link checker is failing on it: https://travis-ci.org/spinnaker/spinnaker.github.io/builds/334900930#L2838

**Comment by davidxia** [comment]
Ah, the link is written in a way that makes it work on spinnaker.io [here](https://www.spinnaker.io/reference/api/) but not on github.com. Good catch.

**Comment by lwander** [comment]
Heh the link checker caught it, not me :wink:

**Pull request closed without merging**
