### PR TITLE
fix(halyard): fix halyard port number

### PR DESCRIPTION
**Pull request by ethanfrogers**
the port number that was listed for the docker container was incorrect.

@lwander PTAL

### CODE REVIEW

**Review by lwander — COMMENTED** [review]
This is meant for serving gate & deck traffic after Spinnaker is deployed remotely

**Comment by ethanfrogers** [comment]
facepalm

**Comment by edwinavalos** [comment]
Lol

**Comment by lwander** [comment]
Heh no worries

**Pull request closed without merging**
