### PR TITLE
feat(docs): highlight current page nav root when collapsed

### PR DESCRIPTION
**Pull request by ghost**
When collapsing a section of nav that contains a link to the current page the highlight indicating the current page is hidden.  This PR introduces a highlight to collapsed nav entries to indicate current location in the hierarchy.

Notice the changing nav highlight in this GIF:

highlighting_parent_els

### CODE REVIEW

**Comment by lwander** [comment]
neat!

**Review by dorbin — APPROVED** [review]
Approve, pending fix for whatever broke the build ;)

**Comment by ghost** [comment]
It looks like travis is having trouble fetching dependencies over the network.  Will retry if it fails again.

**Comment by ghost** [comment]
OK, finally passed, must have been network weather.  Will leave until Monday a.m. before merging.

**Pull request merged**
