### PR TITLE
fix(guides): Use primaryName/previousName instead of primaryClass/previousClass for Orca DualExecutionRepository

### PR DESCRIPTION
**Pull request by dragon3**
## WHAT

This pull request updates the guide "**Orca: Redis to SQL Migration**" to use `primaryName/previousName` instead of `primaryClass/previousClass` for Orca `DualExecutionRepository`.

## WHY

From: [DualExecutionRepository for Orca doesn't work since InstrumentedProxy introduced](https://github.com/spinnaker/spinnaker/issues/5381)

`com.netflix.spinnaker.orca.sql.telemetry.SqlInstrumentedExecutionRepository` was already deleted and currently using class name for `DualExecutionRepository` doesn't work because of https://github.com/spinnaker/spinnaker/issues/5381

It's better to use bean name now.

### CODE REVIEW

**Review by robzienert — APPROVED** [review]

**Comment by robzienert** [comment]
Thanks!

**Comment by dragon3** [comment]
Thank you for the review!
Will it be published soon?

**Comment by dragon3** [comment]
Thank you for the merge and publishing.
I've confirmed it.

Screen Shot 2020-03-02 at 7 51 00

https://www.spinnaker.io/guides/operator/orca-redis-to-sql/

Thanks!

**Comment by SoumyaMaitra** [comment]
Thank you!

**Pull request merged**
