### PR TITLE
chore(gemfile): upgrade nokokigi in Gemfile.lock after security vuln

### PR DESCRIPTION
**Pull request by dorbin**

### CODE REVIEW

**Comment by ttomsu** [comment]
Logs say:

```
Downloading html-proofer-3.9.3 revealed dependencies not in the API or the
lockfile (nokogiri (~> 1.8.1)).
Either installing with `--full-index` or running `bundle update html-proofer`
should fix the problem.
```

**Comment by ttomsu** [comment]
Ping - any progress here?

**Comment by dorbin** [comment]
Ignore a problem long enough and it goes away. :see_no_evil: 
The repo no longer shows the vulnerabilty warning.

**Comment by dorbin** [comment]
#1181

**Pull request closed without merging**
