### PR TITLE
docs(release cal): Add a release calendar that people can subscribe to

### PR DESCRIPTION
**Pull request by plumpy**

### CODE REVIEW

**Review by ezimanyi — APPROVED** [review]
📆 💯

**Review by maggieneterval — APPROVED** [review]
📆 🍡 💯 🙏

**Comment by dorbin** [comment]
💀 🦨 💔 🙈

**Review by dorbin — APPROVED** [review]
Er, I mean 👍 💯 🥇 :shipit:

**Review by ethanfrogers — APPROVED** [review]

**Pull request merged**
