### PR TITLE
docs(aws install): Put warning about stale AWS-EC2 install doc with link to temporary alternative

### PR DESCRIPTION
**Pull request by akshayabd**
Not sure if its prominent enough, but here is what it looks like:

Screen Shot 2020-03-27 at 3 04 24 PM

### CODE REVIEW

**Review by dorbin — APPROVED** [review]
LGTM
@brian-armory what say ye?

**Comment by 317brian** [comment]
There's a missing period at the end, and you need a comma after `meantime`, @akshayabd. Other than that, LGTM!

**Comment by akshayabd** [comment]
Added:

Screen Shot 2020-03-27 at 4 10 57 PM

**Comment by akshayabd** [comment]
With the comma after "meantime":

Screen Shot 2020-03-27 at 4 13 08 PM

**Review by 317brian — APPROVED** [review]

**Comment by aleon1220** [comment]
I have seen the PRS:
[1763](https://github.com/spinnaker/spinnaker.github.io/pull/1763) ans [1797](https://github.com/spinnaker/spinnaker.github.io/pull/1797/files) 
Those steps talk about installing spinnaker in EKS. How about addin an AWS Account provider via halyard so you can deploy EC2 stuff with spinnaker??
how will that work in the future?
@brian-armory

**Pull request merged**
