### PR TITLE
Replace outdated screenshot of new app dialogue

### PR DESCRIPTION
**Pull request by davidxia**
referenced from https://www.spinnaker.io/guides/tutorials/codelabs/kubernetes-source-to-prod/#1-create-a-spinnaker-application

### CODE REVIEW

**Comment by davidxia** [comment]
My updated screenshot is based on halyard spinnaker version 1.5.2 and also master-latest-unvalidated. Not sure about older versions.

Related slack discussion https://spinnakerteam.slack.com/team/U4R3XHBT4

**Comment by lwander** [comment]
Thanks @davidxia - I think there's a typo in my email address ;) google.com is missing an _e_

**Comment by davidxia** [comment]
woops. I should've just used foo@bar.com

**Comment by lwander** [comment]
No worries

**Pull request merged**
