### PR TITLE
docs(aws): AWS-EKS.MD referenced file fails on AWS

### PR DESCRIPTION
**Pull request by TechnoRoss**
version of K8s is too old (1.10)

### CODE REVIEW

**Comment by 317brian** [comment]
@akshayabd is finding out who owns this and getting it updated something the AWS SIG can do?

**Comment by akshayabd** [comment]
@brian-armory - ack, will follow up. The change is pretty small to make in the file - just need to find out what the process is for editing the file

**Comment by akshayabd** [comment]
Hey @TechnoRoss! Thanks again for bringing this bug to our attention. The owner of the yaml file has been notified of this and hopefully it will be fixed soon, and there won't be a need to add extra documentation to fix the file.

**Comment by TechnoRoss** [comment]
Thanks for letting me know

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by 317brian** [comment]
I'll go ahead and close this PR since there's an issue tracking it: https://github.com/spinnaker/spinnaker.github.io/issues/1548. We can file another PR with a workaround if it doesn't get fixed soon.

**Pull request closed without merging**
