### PR TITLE
Change email providers table

### PR DESCRIPTION
**Pull request by rago-actions**
Hi Team,
Email providers from previous did not render well, so I changed it. 

Please review and merge it. if there is anyway i can view it before it goes into the master.

### CODE REVIEW

**Comment by dorbin** [comment]
@rago-actions 
Ramesh, can you take a look at the conflicts? Thanks!

**Comment by rago-actions** [comment]
@dorbin  did not notice, I just resolved. Thanks for reminding me.

**Comment by rago-actions** [comment]
@dorbin do we have a chance to pull the code locally and build site locally to view the changes whether they render properly.

**Comment by dnilasor** [comment]
Hey @rago-actions, YES you can do that. There are a few methods described in the readme for this repo but the easiest is the docker method, it's 2 commands (Dockerfile is in the root dir):
https://s.armory.io/L1upqW7m
https://github.com/spinnaker/spinnaker.github.io#local-preview

**Comment by rago-actions** [comment]
@dorbin  @dnilasor I verified locally, the table rendered nicely this time.

**Comment by aleon1220** [comment]
> Hey @rago-actions, YES you can do that. There are a few methods described in the readme for this repo but the easiest is the docker method, it's 2 commands (Dockerfile is in the root dir):
> https://s.armory.io/L1upqW7m
> https://github.com/spinnaker/spinnaker.github.io#local-preview

Thanks for that.
Print screen here
Screenshot from 2020-07-23 10-51-31

**Review by dorbin — APPROVED** [review]
Thanks @rago-actions !

**Pull request merged**
