### PR TITLE
chore(authz/ldap): Remove self-link

### PR DESCRIPTION
**Pull request by kowshikRoy**

### CODE REVIEW

**Review by dorbin — COMMENTED** [review]
@kowshikRoy Thanks for the PR. Good catch! 

I wonder if we should just delete this "next steps" section entirely. I mean, reading the *overview* covering a topic of which we're already into the details doesn't sounds like a next step, IMO.
@brian-armory , what say ye?

**Comment by 317brian** [comment]
@dorbin that makes sense to me

**Comment by dorbin** [comment]
@kowshikRoy , you want to go ahead with that?

**Comment by kowshikRoy** [comment]
@dorbin I created a new pull request. Because I mistakenly create PR from the master branch. My sincere apologies.
Please see here: #1729

**Comment by 317brian** [comment]
Thanks @kowshikRoy for doing this. I'll go ahead and close this PR and merge the other one.

**Pull request closed without merging**
