### PR TITLE
docs(notifications): Microsoft Teams notification instructions

### PR DESCRIPTION
**Pull request by jeffreycoe**
This is in reference to issue https://github.com/spinnaker/spinnaker/issues/5826.

### CODE REVIEW

**Review by dorbin — APPROVED** [review]
LGTM. Thanks @jeffreycoe

**Comment by dorbin** [comment]
@jeffreycoe, this is fine, but branch is out of date, and I don't see the usual option to merge in the latest base. Can you do that, then it'll auto merge. Thanks!

**Comment by dorbin** [comment]
@jeffreycoe (or maybe that just happened automatically, so nvm. :) )

**Comment by jeffreycoe** [comment]
@dorbin It was me -- I happened to be on GitHub already and saw the notification pop up. 👍  This issue happened with my other PRs, so I'll have to check our org permissions.

**Pull request merged**
