### PR TITLE
docs(setup) fixed incorrect redirective resulting from setup nav refa…

### PR DESCRIPTION
**Pull request by dorbin**
…ctor

### CODE REVIEW

**Comment by lwander** [comment]
Doesn't this need to be done for all the docs that were moved?

**Comment by dorbin** [comment]
@lwander , I'll go through and check again, but I did add redirectives as needed, and I'm pretty sure most of them use the correct path. Stand by...

**Comment by dorbin** [comment]
@lwander 
spoke too soon

**Review by lwander — APPROVED** [review]
Thanks!

**Pull request merged**
