### PR TITLE
feat(sigs): sig on-boarding

### PR DESCRIPTION
**Pull request by bpowell**

### CODE REVIEW

**Comment by bpowell** [comment]
@aglover @pstout @duftler @skim1420

**Comment by aglover** [comment]
Curious if there are leads other than Alex?

**Comment by alexmbe** [comment]
@aglover talking with a few folks, but no takers yet, would like to get started on organizing the first meeting with the community, gathering the pain points and crafting the roadmap.

**Comment by bpowell** [comment]
@aglover we have added another lead, @okundzich

**Comment by aglover** [comment]
This is great - can't wait wait to see what comes out of this SIG!

**Pull request merged**
