### PR TITLE
feat(sig/security): list sig-security

### PR DESCRIPTION
**Pull request by bpowell**
@aglover @pstout @duftler @skim1420 @helenelau

### CODE REVIEW

**Review by lin-hua-cheng — APPROVED** [review]
looking forward to this sig!

**Comment by ttomsu** [comment]
I think this still needs to be approved by either the steering committee or the toc (I forget which one).

**Comment by pstout** [comment]
The steering committee approved the creation of this SIG at our meeting on January 23rd.

**Comment by bpowell** [comment]
@pstout is this good to be merged or is there something else we need to do? Just want to make sure I have all the boxes checked

**Review by duftler — APPROVED** [review]
LGTM.

**Pull request merged**
