### PR TITLE
docs(spinnaker): add Plaid to user list

### PR DESCRIPTION
**Pull request by ikemonn**
Hi, [Plaid](https://plaid.co.jp/) is a company which provides CX improvement tool "[KARTE](https://karte.io/)" in Japan.
We are now using spinnaker at multi-cloud(AWS/GCP) as the main CD tool.
We talked about it on [Japan tech event](https://builderscon.io/tokyo/2018/).([Slide](https://speakerdeck.com/ikemonn/builderscon-tokyo-2018))
It would be great if we can be on the user list!

### CODE REVIEW

**Comment by ikemonn** [comment]
@lwander 
If it is not too much trouble for you,  could you review this?

I'm writing tech blog about Spinnaker.
I'm very happy if I can introduce about Spinnaker with our service logo at community page 😄 

I'm sorry for your inconvenience.

**Review by lwander — APPROVED** [review]
LGTM! Will let our tech writer @dorbin give one final review -- he should be in the office soon.

**Review by dorbin — APPROVED** [review]
:+1: 
Thanks, @ikemonn !

**Comment by ikemonn** [comment]
Thanks a lot!

**Pull request merged**
