### PR TITLE
Update permissions words in s3.md

### PR DESCRIPTION
**Pull request by emjburns**
I believe this is the correct wording for the front50 configuration. In the process of testing and verifying.

### CODE REVIEW

**Review by lwander — APPROVED** [review]

**Comment by lwander** [comment]
Can you link to what `s3` permissions are?

**Comment by emjburns** [comment]
@lwander how much of AWS / IAM are we expecting people to understand? Do you mean link to what giving permissions to access `s3` means, or the subset of s3 permissions which is required?

**Comment by lwander** [comment]
I'd say we should at least describe how to do it or link to an aws page that shows you how.

**Comment by dorbin** [comment]
If we're talking about what needs to be done to set up s3 permissions, separate from anything Spinnaker specific, then we should just link out to the AWS page that explains it. [This one](https://docs.aws.amazon.com/AmazonS3/latest/dev/s3-access-control.html)?

**Comment by emjburns** [comment]
@dorbin for aws `s3`, there are two types of permissions: 
- a user or role can do things in s3
```{
  "Version": "2012-10-17",
  "Statement":[{
    "Effect": "Allow",
    "Action": "s3:*",
    "Resource": "*"
    }
  ]
}
```
- bucket is allowed to be modified by users/roles (the link that you shared talks about that)

I'll add some words about what is needed, but I can't find a specific example in the aws documentation..

**Comment by dorbin** [comment]
There's [this](https://docs.aws.amazon.com/AmazonS3/latest/dev/access-control-overview.html#access-control-resources-manage-permissions-basics). Is that suffficient?

**Comment by emjburns** [comment]
@dorbin I linked to https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html - can you let me know which you think is better?

**Comment by dorbin** [comment]
:+1:  the link you just posted, @emjburns 
LGTM

**Pull request merged**
