### PR TITLE
Update Gateway troubleshooting FAQ

### PR DESCRIPTION
**Pull request by norajam**
Update one more FAQ for gateway service can't be connected

### CODE REVIEW

**Review by ezimanyi — COMMENTED** [review]
Thanks for the addition to the FAQ!

When redis is unavailable, does the error manifest itself with the exact error message noted in this FAQ?  If not, I'd suggest moving this into a separate question to keep this question focused just on resolving that particular error.

Also, suggested a few minor edits to the wording:
If you have a local deployment of Spinnaker, ensure that Redis is available at the configured address (`localhost:6379` by default).  If not, start redis by running `sudo systemctl enable redis-server && sudo systemctl start redis-server` and restart spinnaker by running `sudo systemctl restart spinnaker`.

**Comment by norajam** [comment]
Hi Eric,

Good suggestion for the words!

The error happens without a clear message, it's linked to this exact message. 

The root cause is in local deployment, redis-server is used as the cache service for those Spinnaker micro components. However, users only see above exact message when they access gateway.

**Comment by ezimanyi** [comment]
@luhaixun : Sounds good, then I think it makes sense to leave it in this question.  So if you just add a commit to update the wording per above, I can merge this.  Thanks!

**Comment by norajam** [comment]
@ezimanyi I add a new commit, please let me if any questions.

**Comment by ezimanyi** [comment]
This looks great, thanks!

**Review by ezimanyi — APPROVED** [review]

**Pull request merged**
