### PR TITLE
docs(ecs): Fix references to ECS name

### PR DESCRIPTION
**Pull request by clareliguori**
Correct product name is Amazon ECS as seen on https://aws.amazon.com/ecs/

### CODE REVIEW

**Review by dorbin — COMMENTED** [review]
@clareliguori 
On the AWS page you linked, it appears they are calling it "Amazon ECS" throughout, for all mentions. With that in mind, you wanna go ahead and change other references in this doc? Like...

s/A Spinnaker server group maps to an ECS service/A Spinnaker server group maps to an Amazon ECS service/

**Comment by clareliguori** [comment]
@dorbin I was told before for slides that we only have to refer to the Amazon bit the first time, but you're right that doesn't seem to be the preference for documentation. [Our public docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-blue-green.html) also repeatedly refer to Amazon ECS. Will fix the rest in this PR

**Comment by clareliguori** [comment]
@dorbin Can you re-review?

**Review by dorbin — APPROVED** [review]
Looks good, @clareliguori 
Thanks for the update!

**Comment by clareliguori** [comment]
@dorbin Can you merge? I need to go resolve some merge conflicts once this is in :)

**Pull request merged**
