### PR TITLE
fix(artifacts): fix s3 object example

### PR DESCRIPTION
**Pull request by ethanfrogers**
fixing the example for defining an s3 object artifact. s/name/reference

### CODE REVIEW

**Comment by ethanfrogers** [comment]
@lwander @benjaminws PTAL

**Review by lwander — APPROVED** [review]
Isn't name also the path?

**Comment by ethanfrogers** [comment]
@lwander good point. i'll add it back. i got thrown off at first because the example didn't work.

**Comment by ethanfrogers** [comment]
@lwander fixed. merge when ready!

**Pull request merged**
