### PR TITLE
Update configure-redis-usage.md

### PR DESCRIPTION
**Pull request by snalvi**
300s = 5min

### CODE REVIEW

**Comment by plumpy** [comment]
Thanks for the PR! Given the conflicting statements, I was curious if the default was actually 300 seconds or 600 seconds. I went to check and the answer is (...drumroll... :drum: ) [30 seconds](https://github.com/spinnaker/clouddriver/blob/e9ca4af27de478278edf36e925f735d5946d31a3/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfigurationProperties.groovy#L29)!

So it turns on the docs are wrong twice. Do you think you could update it to say 30 seconds? Thanks so much!

**Review by snalvi — COMMENTED** [review]
Interval is 30s by default
Timeout is 300s / 5m by default
https://github.com/spinnaker/clouddriver/blob/e9ca4af27de478278edf36e925f735d5946d31a3/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/core/RedisConfigurationProperties.groovy#L29

**Review by plumpy — APPROVED** [review]
Oh sorry, I was reading the diff wrong! I thought the link you changed was about the interval.

Thanks for fixing this!

**Comment by snalvi** [comment]
Waiting on the merge to close off the PR

**Pull request merged**
