### PR TITLE
Add link to kube v2 on providers page

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
@lwander @dorbin

**Comment by lwander** [comment]
We're intentionally leaving the docs off the index for now, since we still have some issues to close out: https://github.com/spinnaker/spinnaker/milestone/38

**Comment by lwander** [comment]
Sorry to close this though! Thanks for the consideration :)

**Comment by davidxia** [comment]
Gotcha. I should've noticed that.

**Comment by lwander** [comment]
No worries at all

**Pull request closed without merging**
