### PR TITLE
chore(sizing): Add note about singleton echo and igor.

### PR DESCRIPTION
**Pull request by duftler**

### CODE REVIEW

**Review by lwander — APPROVED** [review]
Are we sure igor is affected as well?

**Comment by duftler** [comment]
Was mainly reflecting what was written here: https://medium.com/@rizza/re-service-resilience-most-services-can-be-safely-increased-71a8b51b215a

**Comment by dblackdblack** [comment]
thanks for the quick docs update on this.

**Comment by duftler** [comment]
Will wait for Rob to weigh in here as well.

**Review by robzienert — APPROVED** [review]

**Pull request merged**
