### PR TITLE
docs(setup): Fix RBAC for kube v2 provider

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
I was getting this error

```
2018-01-19 19:58:18.378 ERROR 27207 --- [pool-4-thread-3] c.n.s.c.o.DefaultOrchestrationProcessor  : com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor$KubectlException: Deploy failed: Error from server (Forbidden): error when retrieving current configuration of:
&{0xc4207ae840 0xc4200418f0 dxia dxia-nginx-deployment STDIN 0xc42000deb0  false}
from server for: "STDIN": deployments.apps "dxia-nginx-deployment" is forbidden: User "system:serviceaccount:dxia:minimal-spinnaker-service-account" cannot get deployments.apps in the namespace "dxia": Unknown user "system:serviceaccount:dxia:minimal-spinnaker-service-account"

	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor.deploy(KubectlJobExecutor.java:368)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.lambda$deploy$6(KubernetesV2Credentials.java:267)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.runAndRecordMetrics(KubernetesV2Credentials.java:292)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.security.KubernetesV2Credentials.deploy(KubernetesV2Credentials.java:267)
	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.deployer.KubernetesHandler.deploy(KubernetesHandler.java:76)
```

~~Did `deployments.app` recently change to `deployments.apps` or was this a typo originally?~~

Update: seems like both `deployments.extensions` and `deployments.app` are needed.

cc @ethanfrogers

**Comment by ethanfrogers** [comment]
@davidxia what kubernetes version are you on?

**Comment by davidxia** [comment]
1.8.5-gke.0. I wasn't using creating deployments before, so I think was broken originally.

**Comment by davidxia** [comment]
bump cc @lwander

**Review by lwander — APPROVED** [review]

**Comment by lwander** [comment]
Sorry for the wait

**Comment by davidxia** [comment]
no worries. Thanks again

**Pull request merged**
