### PR TITLE
Add site search capabilities.

### PR DESCRIPTION
**Pull request by rbuskens**
@tomaslin: please review.

### CODE REVIEW

**Comment by tomaslin** [comment]
Needs a little padding on the left side of search box. 

Feels like the search should be on the other side of the github icon. 

Search results show up in a popup and search links end up in a new window. Would be nice if this was all inline. 

screen shot 2015-12-16 at 9 53 42 am

In Mobile view, it seems like the search box causes a scrollbar to appear

After:
screen shot 2015-12-16 at 9 57 25 am

Before:
screen shot 2015-12-16 at 9 57 17 am

**Comment by tomaslin** [comment]
The sort by relevance button styling seems to be broken. 

screen shot 2015-12-16 at 10 03 43 am

The search button also doesn't seem to display properly

screen shot 2015-12-16 at 10 03 28 am

**Comment by rbuskens** [comment]
Moved the Search box to the left of the GitHub icon. This also "fixed" the padding problem. By changing the configuration settings for this customized search (via http://cse.google.com/cse/setup/basic?cx=003745387005650415533:vjrktimah_0), made the search results appear inline instead of in a popup.

Re: the "Sort by: Relevance" button styling and the search button not displaying properly. These things are handled by the Google Custom Search Engine; it's not obvious to me yet know how much control I have over adjusting these things. I can keep looking, or can file a TODO to fix this later. Which do you prefer?

Also, in Mobile view, the Search bar now appears at the bottom of the window.

**Comment by zanthrash** [comment]
@rbuskens @tomaslin The search button and "relevance/date" toggle are being messed up because bootstrap is applying **box-sizing: padding-box** to everything.  This is a good thing but some 3rd party widgets don't play nice with it.  The following css should fix all the issues that I could see in both desktop and mobile views.  Just paste it at the end of the spinnaker-sight.less file.


```css
.gsc-control-cse *,
.gsc-control-cse *:before,
.gsc-control-cse *:after {
  -webkit-box-sizing: content-box !important;
  -moz-box-sizing: content-box !important;
  box-sizing: content-box !important;
}

.navbar-fixed-top .navbar-collapse {
  max-height: 355px;
}

.navbar-collapse.in {
  overflow-y: inherit ;
}
```

**Comment by tomaslin** [comment]
thanks @zanthrash

**Comment by tomaslin** [comment]
This is good to merge once we got Zan's changes in - pr is here - https://github.com/rbuskens/spinnaker.github.io/pull/1

**Comment by rbuskens** [comment]
@zanthrash - thanks a bunch for the fix!

**Comment by duftler** [comment]
Very cool.

**Pull request merged**
