### PR TITLE
Note how to verify redis changes worked

### PR DESCRIPTION
**Pull request by lwander**

### CODE REVIEW

**Review by dorbin — COMMENTED** [review]
Might work better to say...

"
To confirm this works:
1. Run `hal config generate`.
1. Run `hal deploy apply` 
(etc.)

**Comment by lwander** [comment]
I don't want to make `hal deploy apply` a part of the "verify this works", since ideally the verification shouldn't require making changes to live infra.

**Comment by lwander** [comment]
@dorbin updated

**Review by dorbin — APPROVED** [review]
:+1:

**Pull request merged**
