### PR TITLE
Replace HipChat with Slack

### PR DESCRIPTION
**Pull request by ScottBrenner**
[HipChat is migrating to Slack](https://slackhq.com/atlassian-and-slack-partnership), might as well remove it from the documentation.

### CODE REVIEW

**Review by dorbin — COMMENTED** [review]
Hi, Scott. This sounds like a good idea. 

There are a few other places in the docs that mention HipChat, can you remove it from there too?

**Comment by dorbin** [comment]
@lwander do you know if we are, or need to be, doing anything about existing HipChat support, or do we expect that Slack will handle any incoming HipChat request that anyone has configured?

**Comment by ScottBrenner** [comment]
@dorbin Done!

**Comment by lwander** [comment]
Before we remove it -- what's the migration plan for existing HipChat users?

**Comment by ScottBrenner** [comment]
Been two months, any news?

**Comment by dorbin** [comment]
@ScottBrenner 
I think until @someone_in_the_community does something to change our support for HipChat, or until we know HipChat support is broken, I think we'll have to keep the current doc.

Feel free to re-open this if you determine HipChat's broken or if there's a PR on spinnaker/spinnaker changing this.

**Pull request closed without merging**
